local_backend: true
backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "src/assets/media/content/" # Media files will be stored in the repo under images/uploads
public_folder: "/media/content" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "data"
    label: "General Data"
    files:
      - label: "Contact / Social Media"
        name: "globalSocial"
        file: "src/_data/globalSocial.json"
        fields:
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "Youtube"
            name: "youtube"
            widget: "string"
          - label: "Twitter"
            name: "twitter"
            widget: "string"
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "src/pages/home/home.md"
        fields:
          - {label: "Work Section Button Text", name: "seeMoreBtnText", widget: "string"}
          - {label: "About Section Text", name: "aboutText", widget: "markdown"}
          - {label: "Contact Section Text", name: "contactText", widget: "string"}
  - label: "Videos"
    name: "videos"
    folder: "src/videos"
    summary: "{{title}} {{tags}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "href", widget: "string"}
      - {label: "Text", name: "description", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "relation", collection: "categories", search_fields: ["title"], value_field: "title", display_fields: ["title"], multiple: true, required: false}
      - {label: "Has description page", name: "detail", widget: "boolean", default: false}
  - label: "Categories"
    name: "categories"
    folder: "src/categories"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
